# Disabled rules that are turned off
disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - todo
  - unused_optional_binding
  - empty_count
  - force_cast
  
# Some rules are turned off by default, so you need to opt-in -> run `swiftlint rules` to see all rules
opt_in_rules:
  - empty_count

# Paths to include/exclude during linting. `--path` is ignored if present.
included:
  # - Source
  - Covid News
excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift
# Rules run by `swiftlint analyze` (experimental)
analyzer_rules:
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 130
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)

